app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['namespace'=>'Admin'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::resource('user', 'UserController');
        Route::resource('category', 'CategoryController');
        Route::resource('product', 'ProductController');
    });
});
Route::get('/home','Client\HomeController@index')->name('index');
Route::get('/detail/{id}','Client\HomeController@getDetail')->name('detail');

Route::get('/category/{id}','Client\HomeController@category')->name('category');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Category;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $category;
    public function __construct(Category $category){
        $this->category = $category;
        // $this->related = ['username', 'email', 'passworld'];
    }
    public function index()
    {
        $category = $this->category->get();
        return view('admin.category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->category->fill($request->input())->save();
        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category-> find($id);
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category=$this->category->find($id);
        $category->update([
            'name'=>$request->input('name'),
            'updated_at' => new \DateTime()
        ]);
        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->category->destroy($id);
        return redirect()->back();
    }
}

resources/views/admin/category/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{route('admin.category.store')}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <label for="">name</label>
                    <input type="text" class="form-control" name="name" >
                    <button class="btn btn-success w-100 mt-2">GO</button>
                </form>
            </div>
        </div>
    </div>
    

</body>
</html>

resources/views/admin/category/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{ route('admin.category.update', ['id' => $category->id]) }}" method="post">
                    {!! csrf_field() !!}
                    {{ method_field('PUT') }}
                    <label for="">name</label>
                    <input type="text" class="form-control"  placeholder="{{ $category->name }}" name="name" >
                    <button class="btn btn-success w-100 mt-2">GO</button>
                </form>
            </div>
        </div>
    </div>
    

</body>
</html>

resources/views/admin/category/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <div class="row">
        <div class="col-12">
            <h1>Danh Mục</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($category as $item)
                    <tr>
                        <td>{{$item ->name}}</td>
                        <form action="{{route('admin.category.destroy',['id'=>$item->id])}}" method="post">
                            <td><input class="btn btn-default" type="submit" value="Delete" /></td>
                            <td><input type="hidden" name="_method" value="delete" /></td>
                            {!! csrf_field() !!}
                        </form>
                        <td><button><a href="{{route('admin.category.edit',['id'=>$item->id])}}">edit</a></button></td>
                        </tr>
                    @endforeach
                    <td><button><a href='{{route('admin.category.create')}}'>thêm</a></button></td>
                    
                </tbody>
            </table>
        </div>
    </div>

</body>
</html>

resources/views/admin/category/product.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <table class="table">
        <thead class="bg-dark text-white">
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Intro</th>
        </thead>
        @foreach($product as $item)
        <tr>
            <td>{{$item->id}}</td>
            <td>{{$item->name}}</td>
            <td>{{$item->price}}</td>
            <td>{{$item->intro}}</td>
        </tr>
        @endforeach
    </table>
</body>
</html>