app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['namespace'=>'Admin'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::resource('user', 'UserController');
        Route::resource('category', 'CategoryController');
        Route::resource('product', 'ProductController');
    });
});
Route::get('/home','Client\HomeController@index')->name('index');
Route::get('/detail/{id}','Client\HomeController@getDetail')->name('detail');

Route::get('/category/{id}','Client\HomeController@category')->name('category');

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Category;
use App\Model\Product;
use App\Model\Img;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $category;
    public function __construct(Category $category, Product $product, Img $img){
        $this->category = $category;
        $this->product = $product;
        $this->img = $img;
        // $this->related = ['username', 'email', 'passworld'];
    }
    public function index()
    {
        $product = $this->product->with('imgs')->get();
        return view('admin.product.index', compact('product') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = category::all();
        return view('admin.product.create',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $destination = 'uploads/photos/'; // your upload folder
        $image       = $request->file('url');
        $filename    = $image->getClientOriginalName(); // get the filename
        $image->move($destination, $filename); // move file to destination
        // create a record
        $product = $this->product->create($request->input());
        $img = Img::create(['product_id' => $product->id,'url' => $destination . $filename,]);
    
       
        return redirect()->route('admin.product.index');


        //  $product->cats()->sync($request->cats, false);
        //  Session::flash('flash_message', 'Service successfully added!');
        //  return redirect()->back()->with('success', 'Service Successfully Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->product->with('imgs')->find($id);
        return view('admin.product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product=$this->product->findOrFail($id);
        $product->update($request->only(['name', 'price', 'intro', 'detail']));
        // $product->update([
        //     'name'=>$request->input('name'),
        //     'price' => $request->input('price'),
        //     'intro' => $request->input('intro'),
        //     'detail' => $request->input('detail'),
        // ]);
        $destination = 'uploads/photos/'; // your upload folder
        $image       = $request->file('url');
        $filename    = $image->getClientOriginalName(); // get the filename
        $image->move($destination, $filename); // move file to destination

        $img = $this->img->where('product_id', $id)->first();
        $this->img->where('id', $img->id)->update([
            'url' => $destination . $filename,
        ]);
        return redirect()->route('admin.product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $list_img_array = array();
        $img = Img::where('product_id', $id)->get();
        foreach($img as $item) {
            $list_img_array[] = $item->img_id;
        }
        Img::where('product_id', $id)->delete();
        $product     = $this->product->destroy($id);
        $delete_img = $this->img->whereIn('id',$list_img_array)->delete();
        return redirect()->route('admin.product.index');
        
    }
}

resources/views/admin/product/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{route('admin.product.store')}}" method="post" enctype="multipart/form-data" >
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <label for="">name</label>
                    <input type="text" class="form-control" name="name" >
                    <label for="">price</label>
                    <input type="text" class="form-control" name="price" >
                    <label for="">intro</label>
                    <input type="text" class="form-control" name="intro" >
                    <label for="">detail</label>
                    <input type="text" class="form-control" name="detail" >
                    <br>
                    <select class="mdb-select md-form w-100" name="category_id">
                        <option value="" disabled selected>Danh Mục</option>
                        @foreach ($category as $item)
                            <option value="{{$item->id}}" name="category_id">{{$item->name}}</option>
                            
                        @endforeach
                    </select>
                    <br>
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Example file input</label>
                        <input type="file" class="form-control-file" id="exampleFormControlFile1" name="url" >
                    </div>
                    <button class="btn btn-success w-100 mt-2">GO</button>
                </form>
            </div>
        </div>
    </div>
    

</body>
</html>

resources/views/admin/product/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{ route('admin.product.update', ['id' => $product->id]) }}" method="post"enctype="multipart/form-data"  >
                    {!! csrf_field() !!}
                    {{ method_field('PUT') }}
                    <label for="">name</label>
                    <input type="text" class="form-control"  placeholder="{{ $product->name }}" name="name" >
                    <label for="">price</label>
                    <input type="text" class="form-control"  placeholder="{{ $product->price }}" name="price" >
                    <label for="">intro</label>
                    <input type="text" class="form-control" placeholder="{{ $product->intro }}" name="intro" >
                    <label for="">detail</label>
                    <input type="text" class="form-control" placeholder="{{ $product->detail }}" name="detail" >
                    <label for="">hinh anh</label>
                    <br>
                    @foreach($product->imgs as $img) <img  width="350px" height="350px" src="{{asset($img->url)  }}" alt="" srcset=""> @endforeach
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Example file input</label>
                        <input type="file" class="form-control-file" id="exampleFormControlFile1" name="url" >
                    </div>
                    <button class="btn btn-success w-100 mt-2">GO</button>
                </form>
            </div>
        </div>
    </div>
    

</body>
</html>

resources/views/admin/product/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>user</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">name</th>
                            <th scope="col">price</th>
                            <th scope="col">intro</th>
                            <th scope="col">detail</th>
                            <th scope="col">img</th>
                            <th scope="col">action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($product as $item)
                        <tr>
                            <td>{{$item->name}}</td>
                            <td>{{$item->price}}</td>
                            <td>{{$item->intro}}</td>
                            <td>{{$item->detail}}</td>
                            <td>@foreach($item->imgs as $imgs) <img width="150px" height="150px" src="{{asset($imgs->url)    }}" alt="" srcset=""> @endforeach</td>
                            <form action="{{route('admin.product.destroy',['id'=>$item->id])}}" method="post">
                                <td><input class="btn btn-default" type="submit" value="Delete" /></td>
                                <td><input type="hidden" name="_method" value="delete" /></td>
                                {!! csrf_field() !!}
                            </form>
                            <td><button><a href="{{route('admin.product.edit',['id'=>$item->id])}}">edit</a></button></td>
                            </tr>
                        @endforeach
                        <td><button><a href='{{route('admin.product.create')}}'>thêm</a></button></td>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>