app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['namespace'=>'Admin'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::resource('user', 'UserController');
        Route::resource('category', 'CategoryController');
        Route::resource('product', 'ProductController');
    });
});
Route::get('/home','Client\HomeController@index')->name('index');
Route::get('/detail/{id}','Client\HomeController@getDetail')->name('detail');

Route::get('/category/{id}','Client\HomeController@category')->name('category');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','he he ', 'code'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Model\Users;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $user;
    public function __construct(Users $user){
        $this->user = $user;
        // $this->related = ['username', 'email', 'passworld'];
    }
    public function index()
    {
        $user = $this->user->get();
        return view('admin.users.master', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->user->fill($request->input())->save();
        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->user-> find($id);
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=$this->user->find($id);
        $user->update([
            'username'=>$request->input('username'),
            'email' => $request->input('email'),
            'passworld' => $request->input('passworld'),
            'updated_at' => new \DateTime()
        ]);
        return redirect()->route('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->user->destroy($id);
        return redirect()->back();
    }
}

resources/views/admin/users/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{ route('admin.user.update', ['id' => $user->id]) }}" method="post">
                    {!! csrf_field() !!}
                    {{ method_field('PUT') }}
                    <label for="">username</label>
                    <input type="text" class="form-control"  placeholder="{{ $user->username }}" name="username" >
                    <label for="">email</label>
                    <input type="text" class="form-control"  placeholder="{{ $user->email }}" name="email" >
                    <label for="">password</label>
                    <input type="password" class="form-control" placeholder="{{ $user->passworld }}" name="passworld" >
                    <button class="btn btn-success w-100 mt-2">GO</button>
                </form>
            </div>
        </div>
    </div>
    

</body>
</html>

resources/views/admin/users/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>user</h1>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">user name</th>
                            <th scope="col">email</th>
                            <th scope="col">action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($user as $item)
                        <tr>
                            <td>{{$item -> username}}</td>
                            <td>{{$item -> email}}</td>
                            <form action="{{route('admin.user.destroy',['id'=>$item->id])}}" method="post">
                                <td><input class="btn btn-default" type="submit" value="Delete" /></td>
                                <td><input type="hidden" name="_method" value="delete" /></td>
                                {!! csrf_field() !!}
                            </form>
                            <td><button><a href="{{route('admin.user.edit',['id'=>$item->id])}}">edit</a></button></td>
                            </tr>
                        @endforeach
                        <td><button><a href='{{route('admin.user.create')}}'>thêm</a></button></td>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/admin/users/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{route('admin.user.store')}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <label for="">username</label>
                    <input type="text" class="form-control" name="username" >
                    <label for="">email</label>
                    <input type="text" class="form-control" name="email" >
                    <label for="">password</label>
                    <input type="password" class="form-control" name="passworld" >
                    <button class="btn btn-success w-100 mt-2">GO</button>
                </form>
            </div>
        </div>
    </div>
    

</body>
</html>